JobtechSwe/myskills-web

.env, package-lock.json, package.json, src/App.tsx, src/graphQL.ts, src/index.tsx, src/pages/Login/Login.tsx, src/pages/Profile/Profile.tsx, src/pages/restricted.tsx, src/utils/helpers.ts
This commit mainly adds functionality for restricted routing and graphql auth.
=> Feat: auth routes

Dockerfile, package-lock.json, package.json
**Ticket:** [#https://trello.com/c/QoMdCSHB/47-ci-for-frontend](https://trello.com/c/QoMdCSHB/47-ci-for-frontend)
**Intent:**
Add Dockerfile
=> ci: 🎡 Dockerfile

LICENSE
**Ticket:** [#34](https://trello.com/c/8aUoBHWu/34-add-license-to-myskills-repo)
=> chore: use apache2 license

.travis.yml, infrastructure/openshift/ci/web-Route.yml
**Ticket:** [#https://trello.com/c/uC5pZ0vL/64-add-https-to-web-and-api](https://trello.com/c/uC5pZ0vL/64-add-https-to-web-and-api)
**Intent:**
add tls certificate for Openshift route
=> ci: 🎡 add tls for web route and remove env from travis config

src/generated/myskills.d.ts
**Ticket:** [#71](https://trello.com/c/80gGENpC/71-update-api-schema)
**Intent:**
Update schema to change from county to region
=> fix: update myskills-api schema

.env, .gitignore
Intent: 
re-adding .env file for easier dev-setup
=> chore: re-add .env file

src/components/Grid/Grid.tsx, src/components/Grid/__tests__/__snapshots__/Grid.spec.tsx.snap
**Ticket:** None
**Intent:** Adding grid template functionallity 
- [ ] Firefox
=> style: added grid-template functionallity

src/graphql/__tests__/client.spec.ts, src/graphql/client.ts, src/graphql/mutations/__tests__/addExperience.spec.ts, src/graphql/mutations/addExperience.ts, src/types/index.ts, src/utils/__tests__/helpers.spec.ts, src/utils/helpers.ts, src/views/CreateProfile/AddExperience.tsx
**Ticket:** [#86](https://trello.com/c/x0o5XXMm/86-investigate-where-how-to-persist-register-state)
**Intent:**
Suggestion how we might handle persising the client cache.
- [ ] Firefox
=> feat: persist cache

package-lock.json, src/components/ButtonLink.tsx, src/components/Typography.tsx, src/components/__tests__/__snapshots__/Typography.spec.tsx.snap, src/views/Login/LoginQR.tsx, src/views/Register/Consent.tsx, src/views/Register/Register.tsx
**Ticket:** [#122](https://trello.com/c/wTiTd0JV/122-%C3%B6ppna-p%C3%A5-denna-enhet-logga-in-consent)
**Intent:**
Make it easier to use the site on a smartphone.
Open up the simulator. Navigate to the web-url, Register or Login and press "Öppna i Egendata"
- [ ] Firefox
=> feat: open in app

src/components/Button.tsx, src/components/OccupationsList/__tests__/__snapshots__/OccupationsList.spec.tsx.snap, src/components/SkillsList.tsx, src/components/Tag.tsx, src/components/__tests__/__snapshots__/Button.spec.tsx.snap, src/components/__tests__/__snapshots__/ListItem.spec.tsx.snap, src/theme/theme.ts, src/views/CreateProfile/ChooseProfession.tsx, src/views/CreateProfile/__tests__/__snapshots__/AddEducation.spec.tsx.snap, src/views/CreateProfile/__tests__/__snapshots__/ChooseProfession.spec.tsx.snap, src/views/Login/__tests__/__snapshots__/Login.spec.tsx.snap, src/views/Register/__tests__/__snapshots__/Register.spec.tsx.snap
**Ticket:** [#124](https://trello.com/c/IDIWi78w/124-taggar-yrkesroll)
**Intent:**
Make tags behave according to UX-design.
- [ ] Firefox
=> feat: add basic styling for tags

src/views/CreateProfile/MatchSkills.tsx, src/views/CreateProfile/PreviousOccupationExperience.tsx, src/views/CreateProfile/__tests__/__snapshots__/MatchSkills.spec.tsx.snap
**Ticket:** [#144](https://trello.com/c/KVTX2qb0/144-add-registration-layout-to-experiences)
**Intent:**
Add registration layout to experiences
=> chore: add registration layout to experience view

infrastructure/openshift/ci/web-DeploymentConfig.yml, infrastructure/openshift/ci/web-Route.yml, package.json
**Ticket:** [#145](https://trello.com/c/kDGKFFEp/145-ta-bort-url-till-openshift-cluster-fr%C3%A5n-repo)
**Intent:** Remove URLS upon request
- [ ] Firefox
=> chore: remove urls

src/views/CreateProfile/WorkExperiences.tsx
=> fix: work-experiences would crash if nothing saved

src/views/CreateProfile/SaveCV.tsx
**Intent:**
minor fix for savecv who is currently asking for wrong subfields
=> fix: save cv subfields

src/views/CreateProfile/SaveCV.tsx
**Ticket:** [#159](https://trello.com/c/FkTw5YS8/159-skicka-med-bild-i-save-cv)
**Intent:**
Add image to save cv
=> feat: add image to save-cv

src/assets/icons/dot.svg, src/components/Layout/ProfileLayout.tsx, src/components/ProfileDataCard.tsx, src/components/TagList.tsx, src/components/__tests__/ProfileLayout.spec.tsx, src/generated/myskills.d.ts, src/graphql/client.ts, src/graphql/clientSchema.graphql, src/graphql/resolvers/mutations/updateContactInformation.ts, src/graphql/shared/Mutations.ts, src/utils/helpers.ts, src/views/CreateProfile/AddContactInformation.tsx, src/views/CreateProfile/ChooseProfession.tsx, src/views/CreateProfile/MatchSkills.tsx, src/views/CreateProfile/SaveCV.tsx, src/views/CreateProfile/__tests__/SaveCV.spec.tsx, src/views/Profile/Home.tsx, src/views/Profile/__fixtures__/profileData.js, src/views/Profile/__tests__/Home.spec.tsx, src/views/Profile/__tests__/__snapshots__/Home.spec.tsx.snap
**Ticket:** [#166](https://trello.com/c/7K3bGtDn/166-skicka-med-kontaktuppgifter-i-spara-cv)
**Intent:**
Query for and render profile information
- [ ] Firefox
=> feat: save cv contact information

.travis.yml
=> chore: use jobtechs namespace instead of one of the developers

src/components/Flex.tsx, src/components/__tests__/__snapshots__/Flex.spec.tsx.snap, src/components/__tests__/__snapshots__/ProfileLayout.spec.tsx.snap, src/views/CreateProfile/__tests__/__snapshots__/AddEducation.spec.tsx.snap, src/views/CreateProfile/__tests__/__snapshots__/MatchSkills.spec.tsx.snap, src/views/Login/__tests__/__snapshots__/Login.spec.tsx.snap, src/views/Profile/__tests__/__snapshots__/Home.spec.tsx.snap, src/views/Start/Start.tsx, src/views/Start/__tests__/__snapshots__/Start.spec.tsx.snap
**Ticket:** [#174](https://trello.com/c/jHnKDHVc/174-fixar-f%C3%B6r-start)
**Intent:** Make css changes according to trello card.
- [ ] Firefox
=> fix: change "Start" stuff according to design review

src/components/Tag.tsx, src/components/TagList.tsx, src/views/CreateProfile/__tests__/__snapshots__/MatchSkills.spec.tsx.snap
**Ticket:** [#176](https://trello.com/c/qUafRBTd/176-fixar-f%C3%B6r-kompetenser)
**Intent:** Updates based on designer feedback.
**How to test (optional):** Check comments in Trello and compare this branch towards CI environment.
- [ ] Firefox
=> feat: skill view updates

src/views/CreateProfile/PreviousOccupationExperience.tsx
**Ticket:** [#177](https://trello.com/c/oNM56QVV/177-fixar-f%C3%B6r-erfarenhet-1)
**Intent:** Updates based on designer feedback.
**How to test (optional):** Check comments in Trello and compare this branch towards CI environment.
- [ ] Firefox
=> feat: prev experience view updates

src/components/IllustrationHeader.tsx, src/components/Layout/RegistrationLayout.tsx, src/generated/myskills.d.ts, src/graphql/clientSchema.graphql, src/views/CreateProfile/ChooseProfession.tsx, src/views/CreateProfile/__tests__/__snapshots__/AddEducation.spec.tsx.snap, src/views/CreateProfile/__tests__/__snapshots__/MatchSkills.spec.tsx.snap
**Ticket:** [#175](https://trello.com/c/Hn91RAgf/175-fixar-f%C3%B6r-yrke)
**Intent:**
- [ ] Firefox
=> fix: occupation

src/views/CreateProfile/WhoAmI.tsx
**Ticket:** [#185](https://trello.com/c/T3uICZX5/185-texten-wrappar-inte-i-whoami)
**Intent:**
Text box would grow width if a longer word was written.
=> fix(whoami): word break in whoAmI input

src/components/Button.tsx, src/components/__tests__/__snapshots__/Button.spec.tsx.snap, src/views/CreateProfile/WhoAmI.tsx, src/views/CreateProfile/__tests__/__snapshots__/AddEducation.spec.tsx.snap, src/views/CreateProfile/__tests__/__snapshots__/MatchSkills.spec.tsx.snap, src/views/Login/__tests__/__snapshots__/Login.spec.tsx.snap, src/views/Start/__tests__/__snapshots__/Start.spec.tsx.snap
**Ticket:** [#179](https://trello.com/c/LOKRNdOb/179-fixar-f%C3%B6r-person)
**Intent:** Updates based on designer feedback.
**How to test (optional):** Check comments in Trello and compare this branch towards CI environment.
- [ ] Firefox
=> fix: updates to button and WhoAmI view

src/views/Login/Login.tsx
=> fix: login approval

src/components/EgenData.tsx, src/views/Login/Login.tsx
=> fix: login approved

src/App.tsx, src/components/EgenData.tsx, src/components/ProfileDataCard.tsx, src/views/CreateProfile/UploadImage.tsx, src/views/Profile/Home.tsx, src/views/Profile/UpdateImage.tsx, src/views/Profile/__tests__/Home.spec.tsx, src/views/partials/Image.tsx
=> fix: minor styling for demo

src/components/EgenData.tsx, src/views/CreateProfile/SaveCV.tsx
=> fix: mobile screen height in EgenData-view

src/App.tsx, src/views/Login/Login.tsx, src/views/partials/Image.tsx
**Ticket:** None
**Intent:** Remove linter warnings
- [ ] Firefox
=> chore: remove unused imports

src/App.tsx, src/components/ScrollTop.tsx
**Ticket:** [#189](https://trello.com/c/DFuSaq08/189-scrolla-till-toppen-vid-next-route)
**Intent:**
add scrolltop
- [ ] Firefox
=> feat: scroll top

src/components/EgenData.tsx, src/components/QR.tsx, src/utils/helpers.ts
**Intent:**
Show QR code on all screens for mobile demoing.
- [ ] Firefox
=> feat: qr code desktop

src/components/Timeline/TimelineEntry.tsx, src/components/Timeline/index.tsx
**Ticket:** [#198](https://trello.com/c/nSTUcvqh/198-fix-tidslinje-styling)
**Intent:**
Fix timeline styling
=> fix: timeline styling

package-lock.json, src/views/Profile/UpdateWorkExperiences.tsx
**Ticket:** [#197](https://trello.com/c/MHI75aCG/197-profil-updateworkexperiences-ska-navigera-till-profil)
**Intent:**
profile/updateworkexperiences should have right button text and navigate back to /profile
=> fix: updateworkexperience navigation

src/App.tsx, src/components/ProfileDataCard.tsx, src/views/CreateProfile/AddTraits.tsx, src/views/Profile/Home.tsx, src/views/Profile/UpdateWorkExperiences.tsx
**Ticket:** [#199](https://trello.com/c/DY6NbgoX/199-remove-image-and-contact-information-from-wizard)
**Intent:**
Remove image and contact information for demo purposes
=> fix: shorten wizard and minor styles

src/App.tsx, src/components/Layout/ProfileLayout.tsx, src/components/StepIndicator.tsx, src/components/__tests__/__snapshots__/ProfileLayout.spec.tsx.snap, src/graphql/shared/Mutations.ts, src/graphql/shared/Queries.ts, src/views/CreateProfile/AddContactInformation.tsx, src/views/CreateProfile/AddEducation.tsx, src/views/CreateProfile/AddSkills.tsx, src/views/CreateProfile/AddTraits.tsx, src/views/CreateProfile/WorkExperiences.tsx, src/views/CreateProfile/__tests__/AddTraits.spec.tsx, src/views/CreateProfile/__tests__/__snapshots__/AddEducation.spec.tsx.snap, src/views/CreateProfile/__tests__/__snapshots__/MatchSkills.spec.tsx.snap, src/views/Profile/Home.tsx, src/views/Profile/UpdateContactInformation.tsx, src/views/Profile/UpdatePersonalDescription.tsx, src/views/Profile/UpdateSkills.tsx, src/views/Profile/UpdateTraits.tsx, src/views/partials/ContactInformation.tsx, src/views/partials/MatchSkills.tsx, src/views/partials/Traits.tsx, src/views/partials/WhoAmI.tsx
**Ticket:** [#200](https://trello.com/c/Cp8UJuTY/200-remote-functionality-for-skills-traits-contact-shorten-wizard)
**Intent:**
For demo environment. Shorten wizard and add remote queries and functionality for remaining profile views
- [ ] Firefox
=> feat: traits, contact and skills should have remote functionality

src/components/Layout/Registration.tsx, src/views/CreateProfile/__tests__/__snapshots__/AddEducation.spec.tsx.snap, src/views/CreateProfile/__tests__/__snapshots__/MatchSkills.spec.tsx.snap, src/views/Profile/Home.tsx, src/views/partials/Experiences.tsx, src/views/partials/MatchSkills.tsx, src/views/partials/Traits.tsx
**Intent:**
Apply minor styling changes to "Fortsätt" button. Also apply some null checks.
- [ ] Firefox
=> fix: apply minor styling fixed and null checks
